//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Building.h
//  @ Date : 6/3/2014
//  @ Author : 
//
//


#if !defined(_BUILDING_H)
#define _BUILDING_H

#include "ElevatorSystem.h"

class Building {
public:
    Building(std::vector<Button*> elButtons, std::vector<Button*> flButtons,
             Sensor* sensor, std::vector<Door*> flDoors, Door* elDoor, Engine* engine);
    ElevatorSystem* getElevatorSystem();
    Elevator* getElevator();
    std::vector<Floor*> getFloors();
private:
    ElevatorSystem* m_elSystem;
    std::vector<Floor*> m_floors;
    Elevator* m_elevator;
};

#endif  //_BUILDING_H
