//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Elevator System
//  @ File Name : Button.h
//  @ Date : 6/3/2014
//  @ Author : 
//
//

#ifndef _BUTTON_H
#define _BUTTON_H

#include "Subject.h"

class Button : public Subject {
public:
    enum ButtonType{
        NUMBUTTON,
       // STOPBUTTON,
        OPENBUTTON,
        CLOSEBUTTON
    };

    Button(int floorNumber, ButtonType type = NUMBUTTON);
    void pressButton();
    int getFloorNumber() const;
    ButtonType getType() const;
private:
    void activateButton();

    int m_isActive;
    int m_floorNumber;
    bool m_bulb;
    ButtonType m_type;

};

#endif  //_BUTTON_H
