//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Elevator System
//  @ File Name : Display.h
//  @ Date : 6/3/2014
//  @ Author : 
//
//


#ifndef _DISPLAY_H
#define _DISPLAY_H

#include <string>
#include "Subject.h"

class Display : public Subject {
public:
    static Display* getInstance();
    void setDisplay(int floorNumber, const std::string &direction);
    int getFloorNumber() const;
    std::string getDirection() const;

private:
    Display();
    int m_floorNumber;
    std::string m_direction; // up, down, "-" (meaning that elevator is idle)
    static Display* m_display;
};

#endif  //_DISPLAY_H
