//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Door.h
//  @ Date : 6/3/2014
//  @ Author : 
//
//

#if !defined(_DOOR_H)
#define _DOOR_H

#include "Subject.h"

class Door : public Subject {
public:
    Door();
    void setTimeOut(const int& timeOut);
    void close();
    void open();
    enum Status{
        ISCLOSE,
        ISOPEN
    };

    Status getStatus() const;

private:
    Status m_status;
    int m_timeOut;
};

#endif  //_DOOR_H
