//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : DoorEngine.h
//  @ Date : 6/3/2014
//  @ Author : 
//
//


#if !defined(_DOORENGINE_H)
#define _DOORENGINE_H


class DoorEngine {
private:
	int remainingTime;
};

#endif  //_DOORENGINE_H
