//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : DownwardList.h
//  @ Date : 6/3/2014
//  @ Author : 
//
//


#if !defined(_DOWNWARDLIST_H)
#define _DOWNWARDLIST_H


class DownwardList {
public:
	void load();
private:
	int dstFloorNumber;
};

#endif  //_DOWNWARDLIST_H
