//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ElevatorDoor.h
//  @ Date : 6/3/2014
//  @ Author : 
//
//


#if !defined(_ELEVATORDOOR_H)
#define _ELEVATORDOOR_H


class ElevatorDoor {
private:
	int status;
};

#endif  //_ELEVATORDOOR_H
