//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Elevator System
//  @ File Name : Scheduler.h
//  @ Date : 6/3/2014
//  @ Author : 
//
//

#ifndef _SCHEDULER_H
#define _SCHEDULER_H

#include <set>
#include "Elevator.h"

class Scheduler {
public:
    Scheduler(Elevator* elevator);
	void processRequest(int floorNumber);
    void schedule();
private:
    std::set<int> m_upwardList;
    std::set<int> m_downwardList;
    Elevator* m_elevator;
};

#endif  //_SCHEDULER_H
