//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Elevator System
//  @ File Name : Sensor.h
//  @ Date : 6/3/2014
//  @ Author : 
//
//


#ifndef _SENSOR_H
#define _SENSOR_H

#include "Subject.h"

class Sensor : public Subject, public Observer {
public:
    Sensor();
    void updateV(Subject *subject);
    void setSensor(const int &floorNumber);
    int getFloorNumber() const;
private:
    bool m_status;
    int m_floorNumber;
};

#endif  //_SENSOR_H
