//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Elevator System
//  @ File Name : Subject.h
//  @ Date : 6/3/2014
//  @ Author : 
//
//

#ifndef _SUBJECT_H
#define _SUBJECT_H

#include "Observer.h"
#include <vector>

class Subject {
public:
    void attach(Observer* observer); // elSystem is observer
    void virtual notify(Subject* subject);

    int getDir() const;
protected:
    std::vector<Observer*> m_observers;
    int m_dir;
};

#endif  //_SUBJECT_H
