//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : UpwardList.h
//  @ Date : 6/3/2014
//  @ Author : 
//
//


#if !defined(_UPWARDLIST_H)
#define _UPWARDLIST_H


class UpwardList {
public:
	void load();
private:
	int dstFloorNumber;
};

#endif  //_UPWARDLIST_H
