//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : UpwardList.cpp
//  @ Date : 6/3/2014
//  @ Author : 
//
//


#include "UpwardList.h"

void UpwardList::load() {

}

